# Generated by Django 6.0.2 on 2026-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ocean_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
