# Generated by Django 6.0.2 on 2026-02-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ocean_market', '0002_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='otp',
        ),
    ]
